version: '3.8'
services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./uploaded_images:/code/uploaded_images
    environment:
      - DATABASE_URL=sqlite:///./test_assets.db
